[package]
name = "cryptography"
version = "0.1.0"
authors = ["reeceyang <reeceyang@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.7.0"
